services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - APP_PORT=${APP_PORT}
      - PG_DSN=${PG_DSN}
      - PG_MAX_OPEN_CONNS=${PG_MAX_OPEN_CONNS}
      - PG_MAX_IDLE_CONNS=${PG_MAX_IDLE_CONNS}
    volumes:
      - .:/app
    depends_on:
      - postgres_db

  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
volumes:
  pg_data:
